### ISSUE TITLE
Keyboard shortcut conflicts with text selection

### ISSUE THREAD

**Issue by bzx** [mfouquet/NudgePushShove#12]
Shift+Opt+(arrow) is a shortcut for "Shove", hovewer it conflicts with text selection, when I'm editing a text layer. 

I would like to disable all keyboard shortcuts in this plugin - @mfouquet, could you please implement this option?

**Comment by theo-v** [comment]
This draws the plug-in useless. Since the issue hasn't been resolved in 7 months, I'm removing the plug-in.

**Comment by heymattj** [comment]
Hi mfouquet.
Any updates on this?
I'm experiencing the same problem and cannot justify keeping the plugin installed it's not resolved, unfortunately.
Thanks!
