### ISSUE TITLE
Nudge settings dialog box doesn't show up in Sketch 66

### ISSUE THREAD

**Issue by rodnem** [mfouquet/NudgePushShove#14]
Thanks to check it

**Comment by CalebAmesbury** [comment]
The dialog box doesn't show, and the plugin has stopped working for me.  Even with a fresh install.

**Comment by dan-sblv** [comment]
> The dialog box doesn't show, and the plugin has stopped working for me. Even with a fresh install.

Same issue here

**Comment by ncasares** [comment]
Same issue here. Uninstalled, removed all other plugins but the problem persists.

**Comment by yizuwu** [comment]
Same issue!
