### ISSUE TITLE
Shortcut Issue

### ISSUE THREAD

**Issue by jayhxmo** [mfouquet/NudgePushShove#3]
Great plugin!
One problem though:

Currently, the keyboard shortcuts for push and shove are:
Push -> shift + direction (regular)
Shove -> option + shift + direction

The problem here is, that the option key is used to show the guides / distance. So I will often use option + shift + direction to "push" and see how far an element is from another, without intending to "shove."

Will updated / custom keyboard shortcuts be a feature soon?

**Comment by mfouquet** [comment]
Good idea! Let me see if I can get something worked out.

**Comment by jayhxmo** [comment]
Hey, any updates to this? :)

**Comment by mfouquet** [comment]
I added an option in the Settings that allows you to switch between Option and Command. That's the best I could do unfortunately. If you need something different still, you can try System Preferences > Keyboard > Shortcuts > App Shortcuts > Add. From there just type in the exact name of the menu item (in this case, Up, Down, Left, or Right) and the hotkey. 

Thanks for the feedback and explanation!
